Traceback (most recent call last):
  File "/home/frmuno/anaconda3/envs/jupyterbook/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/frmuno/anaconda3/envs/jupyterbook/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/frmuno/anaconda3/envs/jupyterbook/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/frmuno/anaconda3/envs/jupyterbook/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/frmuno/anaconda3/envs/jupyterbook/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/frmuno/anaconda3/envs/jupyterbook/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/frmuno/anaconda3/envs/jupyterbook/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/frmuno/anaconda3/envs/jupyterbook/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
## Get the data
from urllib.request import urlopen
import xml.etree.ElementTree as ET

#l13_ini_url = 'https://app.parlamento.pt/webutils/docs/doc.xml?path=6148523063446f764c324679626d56304c3239775a57356b595852684c3052685a47397a51574a6c636e52766379394a626d6c6a6157463061585a686379395953556c4a4a5449775447566e61584e7359585231636d45765357357059326c6864476c3259584e5953556c4a4c6e687462413d3d&fich=IniciativasXIII.xml&Inline=true'
#l13_ini_tree = ET.parse(urlopen(l13_ini_url))
l13_ini_file = '../l13_ini.xml'
l13_ini_tree = ET.parse(l13_ini_file)
l14_ini_file = '../l14_ini.xml'
l14_ini_tree = ET.parse(l14_ini_file)

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m/tmp/ipykernel_52473/3893252821.py[0m in [0;36m<module>[0;34m[0m
[1;32m      6[0m [0;31m#l13_ini_tree = ET.parse(urlopen(l13_ini_url))[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m [0ml13_ini_file[0m [0;34m=[0m [0;34m'../l13_ini.xml'[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 8[0;31m [0ml13_ini_tree[0m [0;34m=[0m [0mET[0m[0;34m.[0m[0mparse[0m[0;34m([0m[0ml13_ini_file[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      9[0m [0ml14_ini_file[0m [0;34m=[0m [0;34m'../l14_ini.xml'[0m[0;34m[0m[0;34m[0m[0m
[1;32m     10[0m [0ml14_ini_tree[0m [0;34m=[0m [0mET[0m[0;34m.[0m[0mparse[0m[0;34m([0m[0ml14_ini_file[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/envs/jupyterbook/lib/python3.8/xml/etree/ElementTree.py[0m in [0;36mparse[0;34m(source, parser)[0m
[1;32m   1200[0m     """
[1;32m   1201[0m     [0mtree[0m [0;34m=[0m [0mElementTree[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1202[0;31m     [0mtree[0m[0;34m.[0m[0mparse[0m[0;34m([0m[0msource[0m[0;34m,[0m [0mparser[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1203[0m     [0;32mreturn[0m [0mtree[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1204[0m [0;34m[0m[0m

[0;32m~/anaconda3/envs/jupyterbook/lib/python3.8/xml/etree/ElementTree.py[0m in [0;36mparse[0;34m(self, source, parser)[0m
[1;32m    582[0m         [0mclose_source[0m [0;34m=[0m [0;32mFalse[0m[0;34m[0m[0;34m[0m[0m
[1;32m    583[0m         [0;32mif[0m [0;32mnot[0m [0mhasattr[0m[0;34m([0m[0msource[0m[0;34m,[0m [0;34m"read"[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 584[0;31m             [0msource[0m [0;34m=[0m [0mopen[0m[0;34m([0m[0msource[0m[0;34m,[0m [0;34m"rb"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    585[0m             [0mclose_source[0m [0;34m=[0m [0;32mTrue[0m[0;34m[0m[0;34m[0m[0m
[1;32m    586[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '../l13_ini.xml'
FileNotFoundError: [Errno 2] No such file or directory: '../l13_ini.xml'

