Traceback (most recent call last):
  File "/home/frmuno/anaconda3/envs/jupyterbook/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/frmuno/anaconda3/envs/jupyterbook/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/frmuno/anaconda3/envs/jupyterbook/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/frmuno/anaconda3/envs/jupyterbook/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/frmuno/anaconda3/envs/jupyterbook/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/frmuno/anaconda3/envs/jupyterbook/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/frmuno/anaconda3/envs/jupyterbook/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/frmuno/anaconda3/envs/jupyterbook/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from urllib.request import urlopen
import xml.etree.ElementTree as ET

#oe_url = "http://app.parlamento.pt/webutils/docs/doc.xml?path=6148523063446f764c324679626d56304c3239775a57356b595852684c3052685a47397a51574a6c636e52766379395063734f6e5957316c626e52764a5449775a47386c4d6a4246633352685a47387657456c574a5449775447566e61584e7359585231636d457654305651636d397762334e3059584e426248526c636d466a595738794d4449785433497565473173&fich=OEPropostasAlteracao2021Or.xml&Inline=true"
#oe_tree = ET.parse(urlopen(oe_url))
oe_file = './OE2020r.xml'
oe_tree = ET.parse(oe_file)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m/tmp/ipykernel_556025/2475126478.py[0m in [0;36m<module>[0;34m[0m
[1;32m      5[0m [0;31m#oe_tree = ET.parse(urlopen(oe_url))[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      6[0m [0moe_file[0m [0;34m=[0m [0;34m'./OE2020r.xml'[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 7[0;31m [0moe_tree[0m [0;34m=[0m [0mET[0m[0;34m.[0m[0mparse[0m[0;34m([0m[0moe_file[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/anaconda3/envs/jupyterbook/lib/python3.8/xml/etree/ElementTree.py[0m in [0;36mparse[0;34m(source, parser)[0m
[1;32m   1200[0m     """
[1;32m   1201[0m     [0mtree[0m [0;34m=[0m [0mElementTree[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1202[0;31m     [0mtree[0m[0;34m.[0m[0mparse[0m[0;34m([0m[0msource[0m[0;34m,[0m [0mparser[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1203[0m     [0;32mreturn[0m [0mtree[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1204[0m [0;34m[0m[0m

[0;32m~/anaconda3/envs/jupyterbook/lib/python3.8/xml/etree/ElementTree.py[0m in [0;36mparse[0;34m(self, source, parser)[0m
[1;32m    582[0m         [0mclose_source[0m [0;34m=[0m [0;32mFalse[0m[0;34m[0m[0;34m[0m[0m
[1;32m    583[0m         [0;32mif[0m [0;32mnot[0m [0mhasattr[0m[0;34m([0m[0msource[0m[0;34m,[0m [0;34m"read"[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 584[0;31m             [0msource[0m [0;34m=[0m [0mopen[0m[0;34m([0m[0msource[0m[0;34m,[0m [0;34m"rb"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    585[0m             [0mclose_source[0m [0;34m=[0m [0;32mTrue[0m[0;34m[0m[0;34m[0m[0m
[1;32m    586[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: './OE2020r.xml'
FileNotFoundError: [Errno 2] No such file or directory: './OE2020r.xml'

